<?xml version="1.0" encoding="utf-8"?><!DOCTYPE skybitz [<!ELEMENT skybitz (error, transid? ,(gls | profile | setup | checkstatus | mileage|totalmileage)* , batchnum?)><!ELEMENT error (#PCDATA)><!ELEMENT batchnum (#PCDATA)><!ELEMENT gls (mtsn, dttsstatus?, turnupdate?, turnupdate-iso8601?, activationstatus?, transferdate?, transferdate-iso8601?, shippingaddress?, asset?, messagetype, binary*, extpwr?, serial*, volumetricdata?, latitude?, latitude-iso6709?, longitude?, longitude-iso6709?, speed?, heading?, headingindegrees?, journeydistance?,totaldevicemileage?,temperaturecelsius?, temperaturefahrenheit?, battery?, time, time-iso8601?, quality?, landmark?,address?, skyfence?, idle?,epmflag?,ehmeter?,ehcounter?,ats?, reeferstate?,transid?, messagereceivedtime, messagereceivedtime-iso8601?, devicetype, departurelocation?)><!ELEMENT mtsn (#PCDATA)><!ELEMENT dttsstatus (#PCDATA)><!ELEMENT devicetype (#PCDATA)><!ELEMENT asset (assetid, tractorid?,assettype, owner, ownerscac?, lessee?, lesseescac?, lessor?, lessorscac?, note?, installdate?, installdate-iso8601?, installlocation?, secondaryid?, acctid?, agreementtype?, branchname?, groups?,container?)><!ELEMENT tractorid (#PCDATA)><!ELEMENT assetid (#PCDATA)><!ELEMENT assettype (#PCDATA)><!ELEMENT owner (#PCDATA)><!ELEMENT secondaryid (#PCDATA)><!ELEMENT acctid (#PCDATA)><!ELEMENT agreementtype (#PCDATA)><!ELEMENT branchname (#PCDATA)><!ELEMENT note (#PCDATA)><!ELEMENT lessor (#PCDATA)><!ELEMENT lessee (#PCDATA)><!ELEMENT ownerscac (#PCDATA)><!ELEMENT lessorscac (#PCDATA)><!ELEMENT lesseescac (#PCDATA)><!ELEMENT turnupdate (#PCDATA)><!ELEMENT turnupdate-iso8601 (#PCDATA)><!ELEMENT activationstatus (#PCDATA)><!ELEMENT installdate (#PCDATA)><!ELEMENT installdate-iso8601 (#PCDATA)><!ELEMENT installlocation (installlatitude, installlongitude, installlatitude-iso6709, installlongitude-iso6709, installtime, installtime-iso8601, installlandmark?)><!ELEMENT installlatitude (#PCDATA)><!ELEMENT installlongitude (#PCDATA)><!ELEMENT installlatitude-iso6709 (#PCDATA)><!ELEMENT installlongitude-iso6709 (#PCDATA)><!ELEMENT installtime (#PCDATA)><!ELEMENT installtime-iso8601 (#PCDATA)><!ELEMENT installlandmark (installgeoname, installlocationid?, installcity?, installstate, installcountry, installdistance)><!ELEMENT installgeoname (#PCDATA)><!ELEMENT installlocationid (#PCDATA)><!ELEMENT installcity (#PCDATA)><!ELEMENT installstate (#PCDATA)><!ELEMENT installcountry (#PCDATA)><!ELEMENT installdistance (#PCDATA)><!ELEMENT departurelocation (departurelatitude, departurelongitude, departurelatitude-iso6709, departurelongitude-iso6709, departuretime, departuretime-iso8601?, departurelandmark?)><!ELEMENT departurelatitude (#PCDATA)><!ELEMENT departurelongitude (#PCDATA)><!ELEMENT departurelatitude-iso6709 (#PCDATA)><!ELEMENT departurelongitude-iso6709 (#PCDATA)><!ELEMENT departuretime (#PCDATA)><!ELEMENT departuretime-iso8601 (#PCDATA)><!ELEMENT departurelandmark (departuregeoname, departurelocationid?, departurecity?, departurestate, departurecountry, departuredistance, departurepostal?)><!ELEMENT departuregeoname (#PCDATA)><!ELEMENT departurelocationid (#PCDATA)><!ELEMENT departurecity (#PCDATA)><!ELEMENT departurestate (#PCDATA)><!ELEMENT departurepostal (#PCDATA)><!ELEMENT departurecountry (#PCDATA)><!ELEMENT departuredistance (#PCDATA)><!ELEMENT transferdate (#PCDATA)><!ELEMENT transferdate-iso8601 (#PCDATA)><!ELEMENT shippingaddress (street?, city?, state?, country?, postal?)><!ELEMENT groups (groupname*)><!ELEMENT container (containerid, scac, size?,truckingcompany?, associateddttm, associateddttm-iso8601)><!ELEMENT containerid (#PCDATA)><!ELEMENT scac (#PCDATA)><!ELEMENT size (#PCDATA)><!ELEMENT truckingcompany (#PCDATA)><!ELEMENT associateddttm (#PCDATA)><!ELEMENT associateddttm-iso8601 (#PCDATA)><!ELEMENT groupname (#PCDATA)><!ELEMENT messagetype (#PCDATA)><!ELEMENT binary (inputname, inputid, event?, inputval?, inputstate?, timeofreading?, timeofreading-iso8601?)><!ELEMENT inputid (#PCDATA)><!ELEMENT inputname (#PCDATA)><!ELEMENT inputval (#PCDATA)><!ELEMENT inputstate (#PCDATA)><!ELEMENT timeofreading (#PCDATA)><!ELEMENT timeofreading-iso8601 (#PCDATA)><!ELEMENT event (#PCDATA)><!ELEMENT extpwr (#PCDATA)><!ELEMENT serial (serialtype, serialid, serialname, serialdata, timeofreading?, timeofreading-iso8601?, event?)><!ELEMENT serialtype (#PCDATA)><!ELEMENT serialid (#PCDATA)><!ELEMENT serialname (#PCDATA)><!ELEMENT serialdata (#PCDATA)><!ELEMENT latitude (#PCDATA)><!ELEMENT latitude-iso6709 (#PCDATA)><!ELEMENT longitude (#PCDATA)><!ELEMENT longitude-iso6709 (#PCDATA)><!ELEMENT speed (#PCDATA)><!ELEMENT heading (#PCDATA)><!ELEMENT headingindegrees (#PCDATA)><!ELEMENT journeydistance (#PCDATA)><!ELEMENT totaldevicemileage (#PCDATA)><!ELEMENT temperaturecelsius (#PCDATA)><!ELEMENT temperaturefahrenheit (#PCDATA)><!ELEMENT battery (#PCDATA)><!ELEMENT time (#PCDATA)><!ELEMENT time-iso8601 (#PCDATA)><!ELEMENT quality (#PCDATA)><!ELEMENT landmark (geoname,locationid?,city?, state, country, postal?, distance, direction,geotypename, geoshape?,locationids?)><!ELEMENT geoname (#PCDATA)><!ELEMENT locationid (#PCDATA)><!ELEMENT city (#PCDATA)><!ELEMENT geotypename (#PCDATA)><!ELEMENT state (#PCDATA)><!ELEMENT country (#PCDATA)><!ELEMENT distance (#PCDATA)><!ELEMENT direction (#PCDATA)><!ELEMENT address (street?, city?, state?, country?, postal?)><!ELEMENT street (#PCDATA)><!ELEMENT postal (#PCDATA)><!ELEMENT geoshape (#PCDATA)><!ELEMENT locationids (locationid*)><!ELEMENT idle (idlestatus, idleduration?,idlegap?)><!ELEMENT idlestatus (#PCDATA)><!ELEMENT idleduration (#PCDATA)><!ELEMENT idlegap (#PCDATA)><!ELEMENT epmflag (#PCDATA)><!ELEMENT ehmeter (#PCDATA)><!ELEMENT ehcounter (#PCDATA)><!ELEMENT ats (lsd,meridian,township,range,section)><!ELEMENT lsd (#PCDATA)><!ELEMENT meridian (#PCDATA)><!ELEMENT township (#PCDATA)><!ELEMENT range (#PCDATA)><!ELEMENT section (#PCDATA)><!ELEMENT profile (mtsn, asset, profiletype, profilenum, profileid, profilepwr, profilestatus, time, time-iso8601?, lastupdate?, lastupdate-iso8601?, expiration?, expiration-iso8601?, nextaction?, nextaction-iso8601?, transid?)><!ELEMENT profiletype (#PCDATA)><!ELEMENT profilenum (#PCDATA)><!ELEMENT profileid (#PCDATA)><!ELEMENT profilepwr (#PCDATA)><!ELEMENT profilestatus (#PCDATA)><!ELEMENT lastupdate (#PCDATA)><!ELEMENT lastupdate-iso8601 (#PCDATA)><!ELEMENT expiration (#PCDATA)><!ELEMENT expiration-iso8601 (#PCDATA)><!ELEMENT nextaction (#PCDATA)><!ELEMENT nextaction-iso8601 (#PCDATA)><!ELEMENT setup (assettypedef*)><!ELEMENT assettypedef (assettype,assettypebase,customassettype, assettypeattr*,note*)><!ELEMENT assettypebase (#PCDATA)><!ELEMENT customassettype (#PCDATA)><!ELEMENT assettypeattr (assettypeattrname,assettypeattrval)><!ELEMENT assettypeattrname (#PCDATA)><!ELEMENT assettypeattrval (#PCDATA)><!ELEMENT reeferstate (reefermake, interfacetype, contenttype, controlleron, fuelpercent?, assetbatteryvoltage?, engineon?, enginemode?, enginesize?, enginespeed?, enginerunhours?, engineswitchonhours?, enginestandbyhours?, reeferoperatingstatus?, reeferalarmstatus?, activeprofileslotnumber?, ambienttemperature?, modezone1?, setpointtemperaturezone1?, supplyairtemperaturezone1?, returnairtemperaturezone1?, modezone2?, setpointtemperaturezone2?, returnairtemperaturezone2?, modezone3?, setpointtemperaturezone3?, returnairtemperaturezone3?, reeferremotetemperaturesensor1?, reeferremotetemperaturesensor2?, reeferremotetemperaturesensor3?,  doorstateopen?, doorswitchopen?, remoteswitch1open?, remoteswitch2open?, remotetemperaturesensor1?, remotetemperaturesensor2?, remotetemperaturesensor3?)><!ELEMENT reeferalarmstatus (reeferalarmtype, reeferalarm*)><!ELEMENT reeferalarm (alarmid, alarmactive, alarmdescr?)><!ELEMENT reefermake (#PCDATA)><!ELEMENT interfacetype (#PCDATA)><!ELEMENT contenttype (#PCDATA)><!ELEMENT controlleron (#PCDATA)><!ELEMENT fuelpercent (#PCDATA)><!ELEMENT assetbatteryvoltage (#PCDATA)><!ELEMENT engineon (#PCDATA)><!ELEMENT enginemode (#PCDATA)><!ELEMENT enginesize (#PCDATA)><!ELEMENT enginespeed (#PCDATA)><!ELEMENT enginerunhours (#PCDATA)><!ELEMENT engineswitchonhours (#PCDATA)><!ELEMENT enginestandbyhours (#PCDATA)><!ELEMENT reeferoperatingstatus (#PCDATA)><!ELEMENT activeprofileslotnumber (#PCDATA)><!ELEMENT ambienttemperature (#PCDATA)><!ELEMENT modezone1 (#PCDATA)><!ELEMENT setpointtemperaturezone1 (#PCDATA)><!ELEMENT supplyairtemperaturezone1 (#PCDATA)><!ELEMENT returnairtemperaturezone1 (#PCDATA)><!ELEMENT modezone2 (#PCDATA)><!ELEMENT setpointtemperaturezone2 (#PCDATA)><!ELEMENT returnairtemperaturezone2 (#PCDATA)><!ELEMENT modezone3 (#PCDATA)><!ELEMENT setpointtemperaturezone3 (#PCDATA)><!ELEMENT returnairtemperaturezone3 (#PCDATA)><!ELEMENT reeferremotetemperaturesensor1 (#PCDATA)><!ELEMENT reeferremotetemperaturesensor2 (#PCDATA)><!ELEMENT reeferremotetemperaturesensor3 (#PCDATA)><!ELEMENT doorstateopen (#PCDATA)><!ELEMENT doorswitchopen (#PCDATA)><!ELEMENT remoteswitch1open (#PCDATA)><!ELEMENT remoteswitch2open (#PCDATA)><!ELEMENT remotetemperaturesensor1 (#PCDATA)><!ELEMENT remotetemperaturesensor2 (#PCDATA)><!ELEMENT remotetemperaturesensor3 (#PCDATA)><!ELEMENT reeferalarmtype (#PCDATA)><!ELEMENT alarmid (#PCDATA)><!ELEMENT alarmactive (#PCDATA)><!ELEMENT alarmdescr (#PCDATA)><!ELEMENT transid (#PCDATA)><!ELEMENT checkstatus (transid)><!ELEMENT mileage (mtsn,asset,mileagecapable,mileagesetupstatus,mileagedetails*)><!ELEMENT mileagecapable (#PCDATA)><!ELEMENT mileagesetupstatus (#PCDATA)><!ELEMENT mileagedetails (mileagedate,mileageInMiles, mileageInKM, timestamp)><!ELEMENT mileagedate (#PCDATA)><!ELEMENT mileageInMiles (#PCDATA)><!ELEMENT mileageInKM (#PCDATA)><!ELEMENT timestamp (#PCDATA)><!ELEMENT volumetricdata (volserialdata, skycamera_plan_type?, nearly_empty?, volevent?, voltimeofreading?, voltimeofreading-iso8601?, cube?, floorspace?, emptynoncargo?, triggeredby?, imagelink?, imagetime?, imagetime-iso8601?, imagelocation?)><!ELEMENT volserialdata (#PCDATA)><!ELEMENT volevent (#PCDATA)><!ELEMENT voltimeofreading (#PCDATA)><!ELEMENT voltimeofreading-iso8601 (#PCDATA)><!ELEMENT cube (#PCDATA)><!ELEMENT floorspace (#PCDATA)><!ELEMENT emptynoncargo (#PCDATA)><!ELEMENT triggeredby (#PCDATA)><!ELEMENT imagelink (#PCDATA)><!ELEMENT imagetime (#PCDATA)><!ELEMENT imagetime-iso8601 (#PCDATA)><!ELEMENT imagelocation (imagegeoname, imagelocationid?, imagecity?, imagestate, imagecountry, imagepostal?,  imagelat, imagelon, imagelat-iso6709, imagelon-iso6709)><!ELEMENT imagegeoname (#PCDATA)><!ELEMENT imagelocationid (#PCDATA)><!ELEMENT imagecity (#PCDATA)><!ELEMENT imagestate (#PCDATA)><!ELEMENT imagepostal (#PCDATA)><!ELEMENT imagecountry (#PCDATA)><!ELEMENT imagelat (#PCDATA)><!ELEMENT imagelon (#PCDATA)><!ELEMENT imagelat-iso6709 (#PCDATA)><!ELEMENT imagelon-iso6709 (#PCDATA)><!ELEMENT skycamera_plan_type (#PCDATA)><!ELEMENT nearly_empty (#PCDATA)><!ELEMENT skyfence (skyfencestatus,departureskyfence?,departurelocationid?,arrivalskyfence?,arrivallocationid?)><!ELEMENT skyfencestatus (#PCDATA)><!ELEMENT departureskyfence (#PCDATA)><!ELEMENT arrivalskyfence (#PCDATA)><!ELEMENT arrivallocationid (#PCDATA)><!ELEMENT totalmileage ( mtsn, asset, totaldevicemileage, timestamp) ><!ELEMENT messagereceivedtime (#PCDATA)><!ELEMENT messagereceivedtime-iso8601 (#PCDATA)>]>
<skybitz>
    <error>0</error>
    <gls>
        <mtsn>MTSN-1</mtsn>
        <asset>
            <assetid>1</assetid>
            <assettype>Reefer</assettype>
            <owner>Dummy Corp</owner>
        </asset>
        <messagetype>Event</messagetype>
        <extpwr>0</extpwr>
        <serial>
            <serialtype>2</serialtype>
            <serialid>3</serialid>
            <serialname>Motion</serialname>
            <serialdata>Moving</serialdata>
            <event>R</event>
        </serial>
        <latitude>38.92067</latitude>
        <latitude-iso6709>38°55&apos;14&quot;N</latitude-iso6709>
        <longitude>-94.78069</longitude>
        <longitude-iso6709>94°46&apos;50&quot;W</longitude-iso6709>
        <speed>0.0</speed>
        <heading>S</heading>
        <headingindegrees>159.0</headingindegrees>
        <battery>OK</battery>
        <time>2022/12/28 12:23:04</time>
        <time-iso8601>2022-12-28T12:23:04Z</time-iso8601>
        <quality>0</quality>
        <landmark>
            <geoname>MCI5</geoname>
            <locationid/>
            <city>Lenexa</city>
            <state>KS</state>
            <country>US</country>
            <postal>66219</postal>
            <distance>0.11</distance>
            <direction>E</direction>
            <geotypename>None</geotypename>
            <geoshape>Circular</geoshape>
        </landmark>
        <address>
            <street>16851 West 113th Street</street>
            <city>Lenexa</city>
            <state>KS</state>
            <country>US</country>
            <postal>66219</postal>
        </address>
        <skyfence>
            <skyfencestatus>In</skyfencestatus>
        </skyfence>
        <idle>
            <idlestatus>IDLE</idlestatus>
            <idleduration>0.04</idleduration>
            <idlegap>0</idlegap>
        </idle>
        <epmflag>0</epmflag>
        <messagereceivedtime>2022/12/28 12:24:51</messagereceivedtime>
        <messagereceivedtime-iso8601>2022-12-28T12:24:51Z</messagereceivedtime-iso8601>
        <devicetype>VUE2000</devicetype>
    </gls>
    <gls>
        <mtsn>MTSN-2</mtsn>
        <asset>
            <assetid>2</assetid>
            <assettype>Reefer</assettype>
            <owner>Dummy Corp</owner>
        </asset>
        <messagetype>Scheduled</messagetype>
        <extpwr>0</extpwr>
        <serial>
            <serialtype>2</serialtype>
            <serialid>3</serialid>
            <serialname>Motion</serialname>
            <serialdata>Idle</serialdata>
        </serial>
        <latitude>41.86334</latitude>
        <latitude-iso6709>41°51&apos;48&quot;N</latitude-iso6709>
        <longitude>-72.71117</longitude>
        <longitude-iso6709>72°42&apos;40&quot;W</longitude-iso6709>
        <speed>0.0</speed>
        <heading>N</heading>
        <headingindegrees>9.0</headingindegrees>
        <totaldevicemileage>8036.06</totaldevicemileage>
        <battery>OK</battery>
        <time>2022/12/28 03:19:04</time>
        <time-iso8601>2022-12-28T03:19:04Z</time-iso8601>
        <quality>0</quality>
        <landmark>
            <geoname>Bloomfield</geoname>
            <locationid/>
            <city>Bloomfield</city>
            <state>CT</state>
            <country>US</country>
            <postal>06002</postal>
            <distance>2.72</distance>
            <direction>N</direction>
            <geotypename>GENERIC</geotypename>
            <geoshape>Circular</geoshape>
        </landmark>
        <address>
            <street>103 Old Iron Ore Rd</street>
            <city>Bloomfield</city>
            <state>CT</state>
            <country>US</country>
            <postal>06002</postal>
        </address>
        <skyfence>
            <skyfencestatus>n/a</skyfencestatus>
        </skyfence>
        <idle>
            <idlestatus>IDLE</idlestatus>
            <idleduration>0.72</idleduration>
            <idlegap>0</idlegap>
        </idle>
        <epmflag>0</epmflag>
        <messagereceivedtime>2022/12/28 03:20:50</messagereceivedtime>
        <messagereceivedtime-iso8601>2022-12-28T03:20:50Z</messagereceivedtime-iso8601>
        <devicetype>Kinnect(SHB6510)</devicetype>
    </gls>
    <gls>
        <mtsn>MTSN-3</mtsn>
        <asset>
            <assetid>3</assetid>
            <assettype>Reefer</assettype>
            <owner>Dummy Corp</owner>
        </asset>
        <messagetype>Scheduled</messagetype>
        <extpwr>0</extpwr>
        <serial>
            <serialtype>2</serialtype>
            <serialid>3</serialid>
            <serialname>Motion</serialname>
            <serialdata>Idle</serialdata>
        </serial>
        <latitude>42.07108</latitude>
        <latitude-iso6709>42°4&apos;16&quot;N</latitude-iso6709>
        <longitude>-88.05998</longitude>
        <longitude-iso6709>88°3&apos;36&quot;W</longitude-iso6709>
        <speed>0.0</speed>
        <heading>N</heading>
        <headingindegrees>9.0</headingindegrees>
        <totaldevicemileage>2306.77</totaldevicemileage>
        <battery>OK</battery>
        <time>2022/12/28 09:48:04</time>
        <time-iso8601>2022-12-28T09:48:04Z</time-iso8601>
        <quality>0</quality>
        <landmark>
            <geoname>Rolling Meadows</geoname>
            <locationid/>
            <city>Rolling Meadows</city>
            <state>IL</state>
            <country>US</country>
            <postal>60008</postal>
            <distance>1.81</distance>
            <direction>W</direction>
            <geotypename>GENERIC</geotypename>
            <geoshape>Circular</geoshape>
        </landmark>
        <address>
            <street>2222 Hammond Dr</street>
            <city>Schaumburg</city>
            <state>IL</state>
            <country>US</country>
            <postal>60196</postal>
        </address>
        <skyfence>
            <skyfencestatus>n/a</skyfencestatus>
        </skyfence>
        <idle>
            <idlestatus>IDLE</idlestatus>
            <idleduration>22.78</idleduration>
            <idlegap>0</idlegap>
        </idle>
        <epmflag>0</epmflag>
        <messagereceivedtime>2022/12/28 09:49:10</messagereceivedtime>
        <messagereceivedtime-iso8601>2022-12-28T09:49:10Z</messagereceivedtime-iso8601>
        <devicetype>Kinnect(SHB6510)</devicetype>
    </gls>
    <gls>
        <mtsn>MTSN-4</mtsn>
        <asset>
            <assetid>4</assetid>
            <assettype>Dry Van</assettype>
            <owner>Dummy Corp</owner>
        </asset>
        <messagetype>Event</messagetype>
        <extpwr>0</extpwr>
        <serial>
            <serialtype>2</serialtype>
            <serialid>3</serialid>
            <serialname>Motion</serialname>
            <serialdata>Stop</serialdata>
            <timeofreading>2022/12/27 18:19:29</timeofreading>
            <timeofreading-iso8601>2022-12-27T18:19:29Z</timeofreading-iso8601>
            <event>E</event>
        </serial>
        <latitude>38.87703</latitude>
        <latitude-iso6709>38°52&apos;37&quot;N</latitude-iso6709>
        <longitude>-76.72789</longitude>
        <longitude-iso6709>76°43&apos;40&quot;W</longitude-iso6709>
        <speed>0.0</speed>
        <heading>S</heading>
        <headingindegrees>199.0</headingindegrees>
        <battery>OK</battery>
        <time>2022/12/27 19:20:29</time>
        <time-iso8601>2022-12-27T19:20:29Z</time-iso8601>
        <quality>0</quality>
        <landmark>
            <geoname>Kettering</geoname>
            <locationid/>
            <city>Kettering</city>
            <state>MD</state>
            <country>US</country>
            <postal>20774</postal>
            <distance>3.23</distance>
            <direction>E</direction>
            <geotypename>GENERIC</geotypename>
            <geoshape>Circular</geoshape>
        </landmark>
        <address>
            <street>687 Commerce Dr</street>
            <city>Upper Marlboro</city>
            <state>MD</state>
            <country>US</country>
            <postal>20774</postal>
        </address>
        <skyfence>
            <skyfencestatus>n/a</skyfencestatus>
        </skyfence>
        <idle>
            <idlestatus>IDLE</idlestatus>
            <idleduration>0.76</idleduration>
            <idlegap>0</idlegap>
        </idle>
        <epmflag>0</epmflag>
        <messagereceivedtime>2022/12/27 19:21:38</messagereceivedtime>
        <messagereceivedtime-iso8601>2022-12-27T19:21:38Z</messagereceivedtime-iso8601>
        <devicetype>GXT5002</devicetype>
    </gls>
    <gls>
        <mtsn>MTSN-5</mtsn>
        <asset>
            <assetid>5</assetid>
            <assettype>Dry Van</assettype>
            <owner>Dummy Corp</owner>
        </asset>
        <messagetype>Scheduled</messagetype>
        <extpwr>0</extpwr>
        <serial>
            <serialtype>2</serialtype>
            <serialid>3</serialid>
            <serialname>Motion</serialname>
            <serialdata>Idle</serialdata>
        </serial>
        <latitude>40.08764</latitude>
        <latitude-iso6709>40°5&apos;15&quot;N</latitude-iso6709>
        <longitude>-75.01596</longitude>
        <longitude-iso6709>75°0&apos;57&quot;W</longitude-iso6709>
        <speed>0.0</speed>
        <heading>N</heading>
        <headingindegrees>9.0</headingindegrees>
        <totaldevicemileage>13841.67</totaldevicemileage>
        <battery>OK</battery>
        <time>2022/12/27 23:53:04</time>
        <time-iso8601>2022-12-27T23:53:04Z</time-iso8601>
        <quality>0</quality>
        <landmark>
            <geoname>Northeast Philadelphia</geoname>
            <locationid/>
            <city>Northeast Philadelphia</city>
            <state>PA</state>
            <country>US</country>
            <postal>19149</postal>
            <distance>3.65</distance>
            <direction>NE</direction>
            <geotypename>GENERIC</geotypename>
            <geoshape>Circular</geoshape>
        </landmark>
        <address>
            <street>2800 Red Lion Rd</street>
            <city>Philadelphia</city>
            <state>PA</state>
            <country>US</country>
            <postal>19114</postal>
        </address>
        <skyfence>
            <skyfencestatus>n/a</skyfencestatus>
        </skyfence>
        <idle>
            <idlestatus>IDLE</idlestatus>
            <idleduration>6.78</idleduration>
            <idlegap>0</idlegap>
        </idle>
        <epmflag>0</epmflag>
        <messagereceivedtime>2022/12/27 23:54:42</messagereceivedtime>
        <messagereceivedtime-iso8601>2022-12-27T23:54:42Z</messagereceivedtime-iso8601>
        <devicetype>Kinnect(SHB6510)</devicetype>
    </gls>
    <gls>
        <mtsn>MTSN-6</mtsn>
        <asset>
            <assetid>6</assetid>
            <assettype>Dry Van</assettype>
            <owner>Dummy Corp</owner>
        </asset>
        <messagetype>Scheduled</messagetype>
        <extpwr>0</extpwr>
        <serial>
            <serialtype>2</serialtype>
            <serialid>3</serialid>
            <serialname>Motion</serialname>
            <serialdata>Idle</serialdata>
        </serial>
        <latitude>35.42739</latitude>
        <latitude-iso6709>35°25&apos;39&quot;N</latitude-iso6709>
        <longitude>-80.66476</longitude>
        <longitude-iso6709>80°39&apos;53&quot;W</longitude-iso6709>
        <speed>0.0</speed>
        <heading>SE</heading>
        <headingindegrees>149.0</headingindegrees>
        <totaldevicemileage>2888.63</totaldevicemileage>
        <battery>OK</battery>
        <time>2022/12/28 02:54:34</time>
        <time-iso8601>2022-12-28T02:54:34Z</time-iso8601>
        <quality>0</quality>
        <landmark>
            <geoname>Concord</geoname>
            <locationid/>
            <city>Concord</city>
            <state>NC</state>
            <country>US</country>
            <postal>28025</postal>
            <distance>4.2</distance>
            <direction>W</direction>
            <geotypename>GENERIC</geotypename>
            <geoshape>Circular</geoshape>
        </landmark>
        <address>
            <street>4530 Fortune Ave NW</street>
            <city>Concord</city>
            <state>NC</state>
            <country>US</country>
            <postal>28027</postal>
        </address>
        <skyfence>
            <skyfencestatus>n/a</skyfencestatus>
        </skyfence>
        <idle>
            <idlestatus>IDLE</idlestatus>
            <idleduration>26.44</idleduration>
            <idlegap>0</idlegap>
        </idle>
        <epmflag>0</epmflag>
        <messagereceivedtime>2022/12/28 02:56:30</messagereceivedtime>
        <messagereceivedtime-iso8601>2022-12-28T02:56:30Z</messagereceivedtime-iso8601>
        <devicetype>VUE2000</devicetype>
    </gls>
    <gls>
        <mtsn>MTSN-7</mtsn>
        <asset>
            <assetid>7</assetid>
            <assettype>Dry Van</assettype>
            <owner>Dummy Corp</owner>
        </asset>
        <messagetype>Scheduled</messagetype>
        <extpwr>0</extpwr>
        <serial>
            <serialtype>2</serialtype>
            <serialid>3</serialid>
            <serialname>Motion</serialname>
            <serialdata>Idle</serialdata>
        </serial>
        <latitude>40.53285</latitude>
        <latitude-iso6709>40°31&apos;58&quot;N</latitude-iso6709>
        <longitude>-74.38492</longitude>
        <longitude-iso6709>74°23&apos;6&quot;W</longitude-iso6709>
        <speed>0.0</speed>
        <heading>N</heading>
        <headingindegrees>9.0</headingindegrees>
        <totaldevicemileage>27706.63</totaldevicemileage>
        <battery>OK</battery>
        <time>2022/12/28 02:25:04</time>
        <time-iso8601>2022-12-28T02:25:04Z</time-iso8601>
        <quality>0</quality>
        <landmark>
            <geoname>Edison</geoname>
            <locationid/>
            <city>Edison</city>
            <state>NJ</state>
            <country>US</country>
            <postal>08817</postal>
            <distance>0.87</distance>
            <direction>W</direction>
            <geotypename>GENERIC</geotypename>
            <geoshape>Circular</geoshape>
        </landmark>
        <address>
            <street>2165 NJ-27</street>
            <city>Edison</city>
            <state>NJ</state>
            <country>US</country>
            <postal>08817</postal>
        </address>
        <skyfence>
            <skyfencestatus>n/a</skyfencestatus>
        </skyfence>
        <idle>
            <idlestatus>IDLE</idlestatus>
            <idleduration>0.54</idleduration>
            <idlegap>0</idlegap>
        </idle>
        <epmflag>0</epmflag>
        <messagereceivedtime>2022/12/28 02:26:41</messagereceivedtime>
        <messagereceivedtime-iso8601>2022-12-28T02:26:41Z</messagereceivedtime-iso8601>
        <devicetype>VUE2000</devicetype>
    </gls>
    <gls>
        <mtsn>MTSN-8</mtsn>
        <asset>
            <assetid>8</assetid>
            <assettype>None</assettype>
            <owner>Dummy Corp</owner>
        </asset>
        <messagetype>Event</messagetype>
        <extpwr>0</extpwr>
        <serial>
            <serialtype>2</serialtype>
            <serialid>3</serialid>
            <serialname>Motion</serialname>
            <serialdata>Moving</serialdata>
            <event>R</event>
        </serial>
        <latitude>32.01329</latitude>
        <latitude-iso6709>32°0&apos;48&quot;N</latitude-iso6709>
        <longitude>-102.00303</longitude>
        <longitude-iso6709>102°0&apos;11&quot;W</longitude-iso6709>
        <speed>0.0</speed>
        <heading>N</heading>
        <headingindegrees>9.0</headingindegrees>
        <battery>OK</battery>
        <time>2022/12/28 12:20:04</time>
        <time-iso8601>2022-12-28T12:20:04Z</time-iso8601>
        <quality>0</quality>
        <landmark>
            <geoname>Midland</geoname>
            <locationid/>
            <city>Midland</city>
            <state>TX</state>
            <country>US</country>
            <postal>79701</postal>
            <distance>5.76</distance>
            <direction>E</direction>
            <geotypename>GENERIC</geotypename>
            <geoshape>Circular</geoshape>
        </landmark>
        <address>
            <city>Midland</city>
            <state>TX</state>
            <country>US</country>
            <postal>79701</postal>
        </address>
        <skyfence>
            <skyfencestatus>n/a</skyfencestatus>
        </skyfence>
        <epmflag>0</epmflag>
        <messagereceivedtime>2022/12/28 12:21:23</messagereceivedtime>
        <messagereceivedtime-iso8601>2022-12-28T12:21:23Z</messagereceivedtime-iso8601>
        <devicetype>Kinnect(SHB6510)</devicetype>
    </gls>
    <gls>
        <mtsn>MTSN-9</mtsn>
        <asset>
            <assetid>9</assetid>
            <assettype>Reefer</assettype>
            <owner>Dummy Corp</owner>
        </asset>
        <messagetype>Scheduled</messagetype>
        <extpwr>0</extpwr>
        <serial>
            <serialtype>2</serialtype>
            <serialid>3</serialid>
            <serialname>Motion</serialname>
            <serialdata>Idle</serialdata>
        </serial>
        <latitude>34.23599</latitude>
        <latitude-iso6709>34°14&apos;10&quot;N</latitude-iso6709>
        <longitude>-79.74797</longitude>
        <longitude-iso6709>79°44&apos;53&quot;W</longitude-iso6709>
        <speed>0.0</speed>
        <heading>NW</heading>
        <headingindegrees>319.0</headingindegrees>
        <totaldevicemileage>10659.76</totaldevicemileage>
        <battery>OK</battery>
        <time>2022/12/28 10:39:34</time>
        <time-iso8601>2022-12-28T10:39:34Z</time-iso8601>
        <quality>0</quality>
        <landmark>
            <geoname>QVC</geoname>
            <locationid/>
            <city>Florence</city>
            <state>SC</state>
            <country>US</country>
            <postal>29501</postal>
            <distance>0.17</distance>
            <direction>SW</direction>
            <geotypename>Shipper</geotypename>
            <geoshape>Multi-Point</geoshape>
        </landmark>
        <address>
            <street>2200 TV Rd</street>
            <city>Florence</city>
            <state>SC</state>
            <country>US</country>
            <postal>29501</postal>
        </address>
        <skyfence>
            <skyfencestatus>In</skyfencestatus>
        </skyfence>
        <idle>
            <idlestatus>IDLE</idlestatus>
            <idleduration>0.69</idleduration>
            <idlegap>0</idlegap>
        </idle>
        <epmflag>0</epmflag>
        <messagereceivedtime>2022/12/28 10:40:29</messagereceivedtime>
        <messagereceivedtime-iso8601>2022-12-28T10:40:29Z</messagereceivedtime-iso8601>
        <devicetype>Kinnect(SHB6510)</devicetype>